2018-03-22 13:41:22,154 [MainThread:11800] [utils.execute:90] DEBUG (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-03-22 13:41:22,200 [MainThread:11800] [utils.execute:90] DEBUG (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2018-03-22 13:41:50,368 [Thread-1:18744] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-03-22 13:41:50,398 [Thread-1:18744] [base.get_response:152] WARNING Not Found: /
2018-03-22 13:41:50,414 [Thread-1:18744] [basehttp.log_message:131] WARNING "GET / HTTP/1.1" 404 3042
2018-03-22 13:41:51,595 [Thread-2:8932] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-03-22 13:41:51,598 [Thread-2:8932] [base.get_response:152] WARNING Not Found: /favicon.ico
2018-03-22 13:41:51,599 [Thread-2:8932] [basehttp.log_message:131] WARNING "GET /favicon.ico HTTP/1.1" 404 3075
2018-03-22 13:42:02,115 [Thread-7:7648] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:42:02,170 [Thread-7:7648] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:42:02,171 [Thread-8:3360] [basehttp.log_message:131] INFO "GET /static/js/interapp.js HTTP/1.1" 304 0
2018-03-22 13:42:02,173 [Thread-7:7648] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:42:02,176 [Thread-7:7648] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:11,name:cx.shouji.360.cn,comment:手机号码归属地查询]]>,inters:<QuerySet [[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:42:02,328 [Thread-7:7648] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:42:02,355 [Thread-7:7648] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:42:02,357 [Thread-7:7648] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 3282
2018-03-22 13:42:41,864 [Thread-13:18016] [business.runAndSave:35] DEBUG ==============开始执行测试脚本==============
2018-03-22 13:42:41,865 [Thread-13:18016] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:42:41,868 [Thread-13:18016] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:42:41,868 [Thread-13:18016] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:42:41,914 [Thread-13:18016] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:11,name:cx.shouji.360.cn,comment:手机号码归属地查询]]>,inters:<QuerySet [[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:42:41,917 [Thread-13:18016] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:42:41,917 [Thread-13:18016] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:42:41,918 [Thread-13:18016] [http_request.do_get:38] DEBUG url:http://cx.shouji.360.cn/phonearea.php,params:number=18888888
2018-03-22 13:42:41,918 [Thread-13:18016] [http_request.do_get:51] WARNING 参数格式错误，已忽略
2018-03-22 13:42:41,920 [Thread-13:18016] [http_request.do_get:54] DEBUG 请求地址:http://cx.shouji.360.cn/phonearea.php
2018-03-22 13:42:42,747 [Thread-13:18016] [http_request.do_get:61] ERROR 程序遇到异常=>Traceback (most recent call last):
  File "F:\python-workspace\autotest\utils\http_request.py", line 56, in do_get
    resp,content=h.request(url, headers={'cache-control':'no-cache','Content-Type':'application/x-www-form-urlencoded'})
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1404, in _request
    redirections=redirections - 1)
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1272, in _conn_request
    conn.connect()
  File "D:\python\Python27\lib\site-packages\httplib2\__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

2018-03-22 13:42:42,749 [Thread-13:18016] [business.runAndSave:55] WARNING 验证失败
2018-03-22 13:42:42,750 [Thread-13:18016] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:42:42,765 [Thread-13:18016] [utils.execute:90] DEBUG (0.015) INSERT INTO "result" ("inter_id", "server_id", "req", "resp", "result", "spend", "createtime") VALUES (28, 11, 'number=18888888', NULL, 0, 830, '2018-03-22 05:42:42.750000'); args=[28, 11, u'number=18888888', None, False, 830, u'2018-03-22 05:42:42.750000']
2018-03-22 13:42:42,845 [Thread-13:18016] [business.runAndSave:61] DEBUG 已将[id:126,inter:[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:],server:[id:11,name:cx.shouji.360.cn,comment:手机号码归属地查询],req:number=18888888,resp:None,result:False,spend:830]保存到数据库
2018-03-22 13:42:42,846 [Thread-13:18016] [business.runAndSave:62] DEBUG ==============测试脚本执行结束==============
2018-03-22 13:42:42,848 [Thread-13:18016] [business.runAndSave:63] INFO 本次共测试：1个接口，成功：0，失败：1
2018-03-22 13:42:42,861 [Thread-13:18016] [basehttp.log_message:131] INFO "GET /executeAll.do?_=1521697322020 HTTP/1.1" 200 31
2018-03-22 13:42:45,391 [Thread-14:7180] [business.listResults:73] INFO 查询执行结果
2018-03-22 13:42:45,394 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "result"."id", "result"."inter_id", "result"."server_id", "result"."req", "result"."resp", "result"."result", "result"."spend", "result"."createtime" FROM "result" ORDER BY "result"."createtime" DESC, "result"."id" ASC LIMIT 100; args=()
2018-03-22 13:42:45,397 [Thread-14:7180] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:42:45,398 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:42:45,401 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:42:45,407 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:42:45,408 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:42:45,411 [Thread-14:7180] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:42:45,413 [Thread-14:7180] [basehttp.log_message:131] INFO "GET /lsresults.do HTTP/1.1" 200 1933
2018-03-22 13:49:21,609 [MainThread:16556] [utils.execute:90] DEBUG (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-03-22 13:49:21,611 [MainThread:16556] [utils.execute:90] DEBUG (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2018-03-22 13:49:45,471 [Thread-1:15040] [basehttp.log_message:131] INFO "GET /api/test.do HTTP/1.1" 200 31
2018-03-22 13:50:03,878 [Thread-7:1444] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-03-22 13:50:03,884 [Thread-7:1444] [base.get_response:152] WARNING Not Found: /
2018-03-22 13:50:03,885 [Thread-7:1444] [basehttp.log_message:131] WARNING "GET / HTTP/1.1" 404 3155
2018-03-22 13:50:14,674 [Thread-13:15812] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:50:14,688 [Thread-13:15812] [utils.execute:90] DEBUG (0.004) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:14,711 [Thread-13:15812] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:14,714 [Thread-13:15812] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:11,name:cx.shouji.360.cn,comment:手机号码归属地查询]]>,inters:<QuerySet [[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:50:14,720 [Thread-14:812] [basehttp.log_message:131] INFO "GET /static/js/interapp.js HTTP/1.1" 304 0
2018-03-22 13:50:14,729 [Thread-13:15812] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:14,733 [Thread-13:15812] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:14,739 [Thread-13:15812] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 3282
2018-03-22 13:50:34,048 [Thread-19:17056] [business.delete:148] DEBUG 删除id为11的服务器信息
2018-03-22 13:50:34,053 [Thread-19:17056] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:50:34,086 [Thread-19:17056] [utils.execute:90] DEBUG (0.031) DELETE FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:50:34,138 [Thread-19:17056] [views.delete:129] DEBUG 删除成功
2018-03-22 13:50:34,141 [Thread-19:17056] [basehttp.log_message:131] INFO "POST /delete.do HTTP/1.1" 200 31
2018-03-22 13:50:34,296 [Thread-20:11372] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:50:34,298 [Thread-20:11372] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:34,299 [Thread-20:11372] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:34,299 [Thread-20:11372] [business.listServersAndInters:94] DEBUG servers:<QuerySet []>,inters:<QuerySet [[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:50:34,302 [Thread-20:11372] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:34,303 [Thread-20:11372] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:34,306 [Thread-20:11372] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 2891
2018-03-22 13:50:49,177 [Thread-22:16508] [utils.execute:90] DEBUG (0.001) BEGIN; args=None
2018-03-22 13:50:49,204 [Thread-22:16508] [utils.execute:90] DEBUG (0.024) INSERT INTO "server" ("name", "comment", "createtime") VALUES ('localhost:8000', '测试', '2018-03-22 05:50:49.181000'); args=[u'localhost:8000', u'\u6d4b\u8bd5', u'2018-03-22 05:50:49.181000']
2018-03-22 13:50:49,280 [Thread-22:16508] [views.saveServer:212] DEBUG 服务器添加成功
2018-03-22 13:50:49,282 [Thread-22:16508] [basehttp.log_message:131] INFO "POST /saveServer.do HTTP/1.1" 200 31
2018-03-22 13:50:49,421 [Thread-23:7776] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:50:49,424 [Thread-23:7776] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:49,440 [Thread-23:7776] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:50:49,441 [Thread-23:7776] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:50:49,446 [Thread-23:7776] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:49,453 [Thread-23:7776] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:50:49,454 [Thread-23:7776] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 3256
2018-03-22 13:50:51,223 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000004D9F128>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,244 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,246 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'id' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [id] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,246 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'service' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [service] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,246 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,247 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'path' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [path] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,250 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,250 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'comment' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [comment] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,250 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'method' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [method] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,252 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'method' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [method] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,252 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'enc' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [enc] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,253 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'enc' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [enc] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,253 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'input' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [input] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,253 [Thread-24:18000] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'output' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [output] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F98>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004CFD630>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004D06D30>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:50:51,256 [Thread-24:18000] [basehttp.log_message:131] INFO "GET /templates/saveinter.html HTTP/1.1" 200 2950
2018-03-22 13:51:21,171 [Thread-25:900] [views.saveinter:178] DEBUG >>>>>{"comment": "\u6d4b\u8bd5\u5730\u5740", "optype": "add", "service": "api", "output": "{\"msg\": \"success\", \"code\": 200}", "method": "GET", "enc": "urlencode", "input": "", "path": "test.do", "csrfmiddlewaretoken": "SEGJWAEa7nLLkzo0Bbgy2kcTjFff40tAneG39fW9ry64ynJcm9cAW1Bk8jCMHfnS", "id": ""}
2018-03-22 13:51:21,174 [Thread-25:900] [business.saveOrUpdateInter:189] DEBUG 保存[id:None,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址]对象
2018-03-22 13:51:21,177 [Thread-25:900] [utils.execute:90] DEBUG (0.001) BEGIN; args=None
2018-03-22 13:51:21,206 [Thread-25:900] [utils.execute:90] DEBUG (0.025) INSERT INTO "inter" ("service", "path", "method", "enc", "input", "output", "comment", "createtime") VALUES ('api', 'test.do', 'GET', 'urlencode', '', '{"msg": "success", "code": 200}', '测试地址', '2018-03-22 05:51:21.181000'); args=[u'api', u'test.do', u'GET', u'urlencode', u'', u'{"msg": "success", "code": 200}', u'\u6d4b\u8bd5\u5730\u5740', u'2018-03-22 05:51:21.181000']
2018-03-22 13:51:21,273 [Thread-25:900] [views.saveinter:191] DEBUG 执行成功
2018-03-22 13:51:21,275 [Thread-25:900] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:51:21,278 [Thread-25:900] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:21,279 [Thread-25:900] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:21,280 [Thread-25:900] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:29,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址], [id:28,service:,path:phonearea.php,method:GET,enc:urlencode,input:number=18888888,output:{"code":0,"data":{"province":"\u5317\u4eac","city":"","sp":"\u79fb\u52a8"}},comment:]]>
2018-03-22 13:51:21,283 [Thread-25:900] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:21,298 [Thread-25:900] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:21,299 [Thread-25:900] [basehttp.log_message:131] INFO "POST /saveinter.do HTTP/1.1" 200 4037
2018-03-22 13:51:28,759 [Thread-26:11576] [business.delete:152] DEBUG 删除id为28的接口信息
2018-03-22 13:51:28,763 [Thread-26:11576] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:51:28,766 [Thread-26:11576] [utils.execute:90] DEBUG (0.001) DELETE FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:28,832 [Thread-26:11576] [views.delete:129] DEBUG 删除成功
2018-03-22 13:51:28,835 [Thread-26:11576] [basehttp.log_message:131] INFO "POST /delete.do HTTP/1.1" 200 31
2018-03-22 13:51:29,151 [Thread-27:17600] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:51:29,154 [Thread-27:17600] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:29,155 [Thread-27:17600] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:29,155 [Thread-27:17600] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:29,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址]]>
2018-03-22 13:51:29,158 [Thread-27:17600] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:29,161 [Thread-27:17600] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:29,164 [Thread-27:17600] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 3156
2018-03-22 13:51:32,111 [Thread-28:15632] [business.runAndSave:35] DEBUG ==============开始执行测试脚本==============
2018-03-22 13:51:32,112 [Thread-28:15632] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:51:32,115 [Thread-28:15632] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:32,117 [Thread-28:15632] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:32,118 [Thread-28:15632] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:29,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址]]>
2018-03-22 13:51:32,118 [Thread-28:15632] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:32,119 [Thread-28:15632] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:32,119 [Thread-28:15632] [http_request.do_get:38] DEBUG url:http://localhost:8000/apitest.do,params:
2018-03-22 13:51:32,121 [Thread-28:15632] [http_request.do_get:54] DEBUG 请求地址:http://localhost:8000/apitest.do
2018-03-22 13:51:33,161 [Thread-29:9280] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-03-22 13:51:33,168 [Thread-29:9280] [base.get_response:152] WARNING Not Found: /apitest.do
2018-03-22 13:51:33,174 [Thread-29:9280] [basehttp.log_message:131] WARNING "GET /apitest.do HTTP/1.1" 404 3185
2018-03-22 13:51:33,180 [Thread-28:15632] [http_request.do_get:57] DEBUG <==>404 Not Found
2018-03-22 13:51:33,183 [Thread-28:15632] [business.runAndSave:55] WARNING 验证失败
2018-03-22 13:51:33,184 [Thread-28:15632] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:51:33,190 [Thread-28:15632] [utils.execute:90] DEBUG (0.003) INSERT INTO "result" ("inter_id", "server_id", "req", "resp", "result", "spend", "createtime") VALUES (29, 1, '', NULL, 0, 1064, '2018-03-22 05:51:33.188000'); args=[29, 1, u'', None, False, 1064, u'2018-03-22 05:51:33.188000']
2018-03-22 13:51:33,272 [Thread-28:15632] [business.runAndSave:61] DEBUG 已将[id:127,inter:[id:29,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址],server:[id:1,name:localhost:8000,comment:测试],req:,resp:None,result:False,spend:1064]保存到数据库
2018-03-22 13:51:33,273 [Thread-28:15632] [business.runAndSave:62] DEBUG ==============测试脚本执行结束==============
2018-03-22 13:51:33,273 [Thread-28:15632] [business.runAndSave:63] INFO 本次共测试：1个接口，成功：0，失败：1
2018-03-22 13:51:33,276 [Thread-28:15632] [basehttp.log_message:131] INFO "GET /executeAll.do?_=1521697814409 HTTP/1.1" 200 31
2018-03-22 13:51:35,990 [Thread-30:5924] [business.listResults:73] INFO 查询执行结果
2018-03-22 13:51:36,005 [Thread-30:5924] [utils.execute:90] DEBUG (0.002) SELECT "result"."id", "result"."inter_id", "result"."server_id", "result"."req", "result"."resp", "result"."result", "result"."spend", "result"."createtime" FROM "result" ORDER BY "result"."createtime" DESC, "result"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:36,016 [Thread-30:5924] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 1; args=(1,)
2018-03-22 13:51:36,020 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 29; args=(29,)
2018-03-22 13:51:36,023 [Thread-30:5924] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:51:36,026 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'server' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Server matching query does not exist.
2018-03-22 13:51:36,032 [Thread-30:5924] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,033 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,040 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,042 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,043 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:51:36,043 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'server' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Server matching query does not exist.
2018-03-22 13:51:36,049 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,055 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,059 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,061 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,072 [Thread-30:5924] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 11; args=(11,)
2018-03-22 13:51:36,073 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'server' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Server matching query does not exist.
2018-03-22 13:51:36,079 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,084 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,088 [Thread-30:5924] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 28; args=(28,)
2018-03-22 13:51:36,089 [Thread-30:5924] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'inter' in template 'results.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\python\Python27\lib\site-packages\django\db\models\fields\related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "D:\python\Python27\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Inter matching query does not exist.
2018-03-22 13:51:36,111 [Thread-30:5924] [basehttp.log_message:131] INFO "GET /lsresults.do HTTP/1.1" 200 2137
2018-03-22 13:51:45,926 [Thread-31:5908] [business.batchdel:160] DEBUG 批量删除id为["127", "126", "125", "124"]的测试结果信息
2018-03-22 13:51:45,928 [Thread-31:5908] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:51:45,930 [Thread-31:5908] [utils.execute:90] DEBUG (0.001) DELETE FROM "result" WHERE "result"."id" IN (124, 125, 126, 127); args=(124, 125, 126, 127)
2018-03-22 13:51:45,994 [Thread-31:5908] [views.batchdel:150] DEBUG 删除成功
2018-03-22 13:51:45,996 [Thread-31:5908] [basehttp.log_message:131] INFO "POST /batchdel.do HTTP/1.1" 200 31
2018-03-22 13:51:46,306 [Thread-32:4328] [business.listResults:73] INFO 查询执行结果
2018-03-22 13:51:46,315 [Thread-32:4328] [utils.execute:90] DEBUG (0.002) SELECT "result"."id", "result"."inter_id", "result"."server_id", "result"."req", "result"."resp", "result"."result", "result"."spend", "result"."createtime" FROM "result" ORDER BY "result"."createtime" DESC, "result"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:46,319 [Thread-32:4328] [basehttp.log_message:131] INFO "GET /lsresults.do HTTP/1.1" 200 1073
2018-03-22 13:51:46,798 [Thread-33:18260] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:51:46,801 [Thread-33:18260] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:46,802 [Thread-33:18260] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:46,803 [Thread-33:18260] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:29,service:api,path:test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:测试地址]]>
2018-03-22 13:51:46,806 [Thread-33:18260] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:46,809 [Thread-33:18260] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:46,828 [Thread-33:18260] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 3156
2018-03-22 13:51:54,813 [Thread-34:2484] [business.delete:152] DEBUG 删除id为29的接口信息
2018-03-22 13:51:54,819 [Thread-34:2484] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:51:54,851 [Thread-34:2484] [utils.execute:90] DEBUG (0.028) DELETE FROM "inter" WHERE "inter"."id" = 29; args=(29,)
2018-03-22 13:51:54,921 [Thread-34:2484] [views.delete:129] DEBUG 删除成功
2018-03-22 13:51:54,924 [Thread-34:2484] [basehttp.log_message:131] INFO "POST /delete.do HTTP/1.1" 200 31
2018-03-22 13:51:55,062 [Thread-35:7952] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:51:55,065 [Thread-35:7952] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:55,069 [Thread-35:7952] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:51:55,069 [Thread-35:7952] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet []>
2018-03-22 13:51:55,075 [Thread-35:7952] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:55,108 [Thread-35:7952] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:51:55,111 [Thread-35:7952] [basehttp.log_message:131] INFO "GET /lsinters.do HTTP/1.1" 200 2376
2018-03-22 13:51:58,680 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000004D9F358>>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,684 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,687 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'id' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [id] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,690 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'service' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [service] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,707 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,710 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'path' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [path] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,713 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'optype' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [optype] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,720 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'comment' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [comment] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,723 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'method' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [method] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,726 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'method' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [method] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,733 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'enc' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [enc] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,736 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'enc' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [enc] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,740 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'input' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [input] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,746 [Thread-36:1384] [base._resolve_lookup:929] DEBUG Exception while resolving variable 'output' in template 'saveinter.html'.
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [output] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: u'8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV'>, 'user': <SimpleLazyObject: <function <lambda> at 0x0000000004D89F28>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000004D8D518>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000004CFDFD0>, u'request': <WSGIRequest: GET '/templates/saveinter.html'>}, {}]"
2018-03-22 13:51:58,750 [Thread-36:1384] [basehttp.log_message:131] INFO "GET /templates/saveinter.html HTTP/1.1" 200 2950
2018-03-22 13:52:14,515 [Thread-37:6708] [views.saveinter:178] DEBUG >>>>>{"comment": "", "optype": "add", "service": "api", "output": "{\"msg\": \"success\", \"code\": 200}", "method": "GET", "enc": "urlencode", "input": "", "path": "/test.do", "csrfmiddlewaretoken": "8H82BiJTzC6WylnPzSnJOr9grqTAcJpDDh8mOX1STNrfM9I1kQjLI8yHg4g7PYjV", "id": ""}
2018-03-22 13:52:14,519 [Thread-37:6708] [business.saveOrUpdateInter:189] DEBUG 保存[id:None,service:api,path:/test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:]对象
2018-03-22 13:52:14,526 [Thread-37:6708] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:52:14,553 [Thread-37:6708] [utils.execute:90] DEBUG (0.008) INSERT INTO "inter" ("service", "path", "method", "enc", "input", "output", "comment", "createtime") VALUES ('api', '/test.do', 'GET', 'urlencode', '', '{"msg": "success", "code": 200}', '', '2018-03-22 05:52:14.545000'); args=[u'api', u'/test.do', u'GET', u'urlencode', u'', u'{"msg": "success", "code": 200}', u'', u'2018-03-22 05:52:14.545000']
2018-03-22 13:52:14,638 [Thread-37:6708] [views.saveinter:191] DEBUG 执行成功
2018-03-22 13:52:14,640 [Thread-37:6708] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:52:14,641 [Thread-37:6708] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:52:14,644 [Thread-37:6708] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:52:14,644 [Thread-37:6708] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:30,service:api,path:/test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:]]>
2018-03-22 13:52:14,648 [Thread-37:6708] [utils.execute:90] DEBUG (0.000) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:52:14,667 [Thread-37:6708] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:52:14,670 [Thread-37:6708] [basehttp.log_message:131] INFO "POST /saveinter.do HTTP/1.1" 200 3145
2018-03-22 13:52:17,437 [Thread-38:11280] [business.runAndSave:35] DEBUG ==============开始执行测试脚本==============
2018-03-22 13:52:17,440 [Thread-38:11280] [business.listServersAndInters:82] INFO 查询接口列表
2018-03-22 13:52:17,443 [Thread-38:11280] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 21; args=()
2018-03-22 13:52:17,444 [Thread-38:11280] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 21; args=()
2018-03-22 13:52:17,447 [Thread-38:11280] [business.listServersAndInters:94] DEBUG servers:<QuerySet [[id:1,name:localhost:8000,comment:测试]]>,inters:<QuerySet [[id:30,service:api,path:/test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:]]>
2018-03-22 13:52:17,448 [Thread-38:11280] [utils.execute:90] DEBUG (0.001) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" ORDER BY "inter"."createtime" DESC, "inter"."id" ASC LIMIT 100; args=()
2018-03-22 13:52:17,476 [Thread-38:11280] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" ORDER BY "server"."createtime" DESC, "server"."id" ASC LIMIT 100; args=()
2018-03-22 13:52:17,477 [Thread-38:11280] [http_request.do_get:38] DEBUG url:http://localhost:8000/api/test.do,params:
2018-03-22 13:52:17,479 [Thread-38:11280] [http_request.do_get:54] DEBUG 请求地址:http://localhost:8000/api/test.do
2018-03-22 13:52:18,484 [Thread-39:10224] [basehttp.log_message:131] INFO "GET /api/test.do HTTP/1.1" 200 31
2018-03-22 13:52:18,486 [Thread-38:11280] [http_request.do_get:57] DEBUG <==>200 OK
2018-03-22 13:52:18,489 [Thread-38:11280] [business.runAndSave:51] DEBUG 验证成功
2018-03-22 13:52:18,492 [Thread-38:11280] [utils.execute:90] DEBUG (0.000) BEGIN; args=None
2018-03-22 13:52:18,523 [Thread-38:11280] [utils.execute:90] DEBUG (0.029) INSERT INTO "result" ("inter_id", "server_id", "req", "resp", "result", "spend", "createtime") VALUES (30, 1, '', '{"msg": "success", "code": 200}', 1, 1014, '2018-03-22 05:52:18.494000'); args=[30, 1, u'', u'{"msg": "success", "code": 200}', True, 1014, u'2018-03-22 05:52:18.494000']
2018-03-22 13:52:18,621 [Thread-38:11280] [business.runAndSave:61] DEBUG 已将[id:128,inter:[id:30,service:api,path:/test.do,method:GET,enc:urlencode,input:,output:{"msg": "success", "code": 200},comment:],server:[id:1,name:localhost:8000,comment:测试],req:,resp:{"msg": "success", "code": 200},result:True,spend:1014]保存到数据库
2018-03-22 13:52:18,622 [Thread-38:11280] [business.runAndSave:62] DEBUG ==============测试脚本执行结束==============
2018-03-22 13:52:18,622 [Thread-38:11280] [business.runAndSave:63] INFO 本次共测试：1个接口，成功：1，失败：0
2018-03-22 13:52:18,625 [Thread-38:11280] [basehttp.log_message:131] INFO "GET /executeAll.do?_=1521697814410 HTTP/1.1" 200 31
2018-03-22 13:52:20,230 [Thread-40:12192] [business.listResults:73] INFO 查询执行结果
2018-03-22 13:52:20,243 [Thread-40:12192] [utils.execute:90] DEBUG (0.002) SELECT "result"."id", "result"."inter_id", "result"."server_id", "result"."req", "result"."resp", "result"."result", "result"."spend", "result"."createtime" FROM "result" ORDER BY "result"."createtime" DESC, "result"."id" ASC LIMIT 100; args=()
2018-03-22 13:52:20,312 [Thread-40:12192] [utils.execute:90] DEBUG (0.001) SELECT "server"."id", "server"."name", "server"."comment", "server"."createtime" FROM "server" WHERE "server"."id" = 1; args=(1,)
2018-03-22 13:52:20,316 [Thread-40:12192] [utils.execute:90] DEBUG (0.000) SELECT "inter"."id", "inter"."service", "inter"."path", "inter"."method", "inter"."enc", "inter"."input", "inter"."output", "inter"."comment", "inter"."createtime" FROM "inter" WHERE "inter"."id" = 30; args=(30,)
2018-03-22 13:52:20,322 [Thread-40:12192] [basehttp.log_message:131] INFO "GET /lsresults.do HTTP/1.1" 200 1327
