2016-10-26 13:07:45,407 [Thread-116:204] [exception.handle_uncaught_exception:124] ERROR Internal Server Error: /lsinters.do
Traceback (most recent call last):
  File "D:\python\Python27\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\python\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\python-workspace\autotest\interapp\views.py", line 39, in lsinters
    return render(request, 'inters.html', ctx)
  File "D:\python\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\python\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "D:\python\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\python\Python27\lib\site-packages\django\template\engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "D:\python\Python27\lib\site-packages\django\template\engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 233, in compile_nodelist
    return parser.parse()
  File "D:\python\Python27\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '%2' from 'forloop.counter%2'
2018-03-22 09:54:36,667 [Thread-20:10948] [base.get_response:152] WARNING Not Found: /favicon.ico
2018-03-22 10:03:29,730 [Thread-46:17032] [base.get_response:152] WARNING Not Found: /
2018-03-22 13:41:50,398 [Thread-1:18744] [base.get_response:152] WARNING Not Found: /
2018-03-22 13:41:51,598 [Thread-2:8932] [base.get_response:152] WARNING Not Found: /favicon.ico
2018-03-22 13:50:03,884 [Thread-7:1444] [base.get_response:152] WARNING Not Found: /
2018-03-22 13:51:33,168 [Thread-29:9280] [base.get_response:152] WARNING Not Found: /apitest.do
